title: Java Creed
description: Java Creed Blog
url: "https://javacreed.com"
permalink: ":title/"
baseurl: "/"

# Comments
discus_identifier: javacreed
txtpen_identifier: javacreed

# Social settings
twitter_url: https://twitter.com/javacreed
facebook_url: https://facebook.com/javacreed
linkedin_url: https://www.linkedin.com/in/javacreed
github_url: https://github.com/javacreed
